

VALIDMESSAGE = 'valid JSON sytax'
INVALIDMESSAGE = 'NOT valid JSON syntax'

JSON_WHITESPACE = ' '
JSON_NEWLINE = '\n'
JSON_COMMA = ','
JSON_COLON = ':'
JSON_LEFTBRACKET = '['
JSON_RIGHTBRACKET = ']'
JSON_LEFTBRACE = '{'
JSON_RIGHTBRACE = '}'
JSON_QUOTE = '"'
JSON_SYNTAX = [JSON_COMMA,JSON_COLON,JSON_QUOTE]
JSON_BLACKLIST = [JSON_COMMA,JSON_COLON,JSON_RIGHTBRACE,JSON_RIGHTBRACKET]